[package]
name = "fernsprechapparat"
version = "0.1.0"
authors = ["Mathias Gottschlag <mgottschlag@gmail.com>"]
edition = "2018"

[dependencies]
pjproject = { git = "https://github.com/mgottschlag/pjproject-rs.git" }
confy = "0.3"
serde = "1.0"
serde_derive = "1.0"
